import React from "react";

function error() {
  return (
    <>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
      <div>This is the error page</div>
    </>
  );
}

export default error;
